//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kskyEntities : DbContext
    {
        public kskyEntities()
            : base("name=kskyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agent { get; set; }
        public DbSet<CTIAgentLog> CTIAgentLog { get; set; }
        public DbSet<CustomerCategory> CustomerCategory { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<EmailAgentWeight> EmailAgentWeight { get; set; }
        public DbSet<EmailContacts> EmailContacts { get; set; }
        public DbSet<EmailDispatchRule> EmailDispatchRule { get; set; }
        public DbSet<EmailFilterRule> EmailFilterRule { get; set; }
        public DbSet<EmailRawBody> EmailRawBody { get; set; }
        public DbSet<EmailRawHeader> EmailRawHeader { get; set; }
        public DbSet<EmailRecord> EmailRecord { get; set; }
        public DbSet<EmailRejectReason> EmailRejectReason { get; set; }
        public DbSet<EmailReplyCan> EmailReplyCan { get; set; }
        public DbSet<EmailSavedAttachment> EmailSavedAttachment { get; set; }
        public DbSet<EmailSavedBody> EmailSavedBody { get; set; }
        public DbSet<EmailScheduleSetting> EmailScheduleSetting { get; set; }
        public DbSet<EmailSentAttachment> EmailSentAttachment { get; set; }
        public DbSet<EmailSentBox> EmailSentBox { get; set; }
        public DbSet<MailGroup> MailGroup { get; set; }
        public DbSet<MailMember> MailMember { get; set; }
        public DbSet<PhoneRecord> PhoneRecord { get; set; }
        public DbSet<RecordCloseApproach> RecordCloseApproach { get; set; }
        public DbSet<Records> Records { get; set; }
        public DbSet<RecordServiceMap> RecordServiceMap { get; set; }
        public DbSet<RecordStatus> RecordStatus { get; set; }
        public DbSet<RecordType> RecordType { get; set; }
        public DbSet<ServiceGroup> ServiceGroup { get; set; }
        public DbSet<ServiceItem> ServiceItem { get; set; }
    }
}
