
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace TTCS.Areas.EmailSrv.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EAgent
{

    public EAgent()
    {

        this.EmailDispatchRule = new HashSet<EEmailDispatchRule>();

        this.EmailDispatchRule1 = new HashSet<EEmailDispatchRule>();

        this.EmailDispatchRule2 = new HashSet<EEmailDispatchRule>();

        this.EmailRecord = new HashSet<EEmailRecord>();

        this.EmailRecord1 = new HashSet<EEmailRecord>();

        this.ERecords = new HashSet<ERecords>();

    }


    public string AgentID { get; set; }

    public string AgentName { get; set; }

    public string AgentPWD { get; set; }

    public string VMPWD { get; set; }

    public Nullable<int> HasVoiceMail { get; set; }

    public string Email { get; set; }

    public string GW32 { get; set; }

    public Nullable<int> Authority { get; set; }

    public string CTILoginID { get; set; }

    public string CTILoginPWD { get; set; }

    public string Name { get; set; }

    public Nullable<int> AutoLogin { get; set; }

    public Nullable<int> AutoLogout { get; set; }

    public string DefaultExten { get; set; }

    public Nullable<System.DateTime> AutoLoginTime { get; set; }

    public Nullable<System.DateTime> AutoLogoutTime { get; set; }

    public Nullable<byte> LocalDistance { get; set; }

    public Nullable<byte> LongDistance { get; set; }

    public Nullable<byte> Mobil { get; set; }

    public Nullable<byte> International { get; set; }

    public string DialContext { get; set; }

    public Nullable<byte> Active { get; set; }

    public string DeptID { get; set; }

    public Nullable<byte> SMSEnable { get; set; }

    public Nullable<byte> FaxEnable { get; set; }

    public Nullable<byte> EmailEnable { get; set; }

    public Nullable<byte> ChatEnable { get; set; }

    public Nullable<byte> GrpRecBoxEnable { get; set; }

    public Nullable<byte> EmailIsLogin { get; set; }



    public virtual ICollection<EEmailDispatchRule> EmailDispatchRule { get; set; }

    public virtual ICollection<EEmailDispatchRule> EmailDispatchRule1 { get; set; }

    public virtual ICollection<EEmailDispatchRule> EmailDispatchRule2 { get; set; }

    public virtual ICollection<EEmailRecord> EmailRecord { get; set; }

    public virtual ICollection<EEmailRecord> EmailRecord1 { get; set; }

    public virtual ICollection<ERecords> ERecords { get; set; }

}

}
