
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace TTCS.Areas.EmailSrv.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EEmailDispatchRule
{

    public int Id { get; set; }

    public Nullable<System.Guid> CustomerId { get; set; }

    public string AgentId1 { get; set; }

    public string AgentId2 { get; set; }

    public string AgentId3 { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }

    public string ModifyBy { get; set; }

    public Nullable<int> ConditionType { get; set; }

    public string Condition { get; set; }

    //public Nullable<bool> AutoDispatch { get; set; }
    public bool AutoDispatch { get; set; }



    public virtual EAgent Agent { get; set; }

    public virtual EAgent Agent1 { get; set; }

    public virtual EAgent Agent2 { get; set; }

    public virtual ECustomers Customers { get; set; }

}

}
