//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCS.Areas.EmailSrv.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmailSrvEntities : DbContext
    {
        public EmailSrvEntities()
            : base("name=EmailSrvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EAgent> Agent { get; set; }
        public DbSet<ECustomers> Customers { get; set; }
        public DbSet<ECustomerCategory> CustomerCategory { get; set; }
        public DbSet<EEmailDispatchRule> EmailDispatchRule { get; set; }
        public DbSet<EEmailFilterRule> EmailFilterRule { get; set; }
        public DbSet<EEmailRawBody> EmailRawBody { get; set; }
        public DbSet<EEmailRawHeader> EmailRawHeader { get; set; }
        public DbSet<EEmailRecord> EmailRecord { get; set; }
        public DbSet<ERecords> Records { get; set; }
        public DbSet<ERecordStatus> RecordStatus { get; set; }
        public DbSet<ERecordType> RecordType { get; set; }
        public DbSet<EServiceGroup> ServiceGroup { get; set; }
        public DbSet<EServiceItem> ServiceItem { get; set; }
        public DbSet<EEmailSavedBody> EmailSavedBody { get; set; }
        public DbSet<EEmailContacts> EmailContacts { get; set; }
        public DbSet<EEmailRejectReason> EmailRejectReason { get; set; }
        public DbSet<EEmailReplyCan> EmailReplyCan { get; set; }
        public DbSet<EEmailScheduleSetting> EmailScheduleSetting { get; set; }
        public DbSet<EMailGroup> MailGroup { get; set; }
        public DbSet<EMailMember> MailMember { get; set; }
        public DbSet<EEmailAgentWeight> EmailAgentWeight { get; set; }
        public DbSet<EEmailSavedAttachment> EmailSavedAttachment { get; set; }
        public DbSet<ERecordServiceMap> RecordServiceMap { get; set; }
        public DbSet<EPhoneRecord> PhoneRecord { get; set; }
        public DbSet<ERecordCloseApproach> RecordCloseApproach { get; set; }
    }
}
